# Assignment 1

![](https://media.giphy.com/media/xT9C25UNTwfZuk85WP/giphy-downsized-large.gif)

Remember the rules of ~Fight~ Code Club:
1. ALWAYS DOCUMENT
2. Cite resources that you use (paste links)
3. Include the names people who you worked with
4. Be neat and organized

## Scrape and Clean data

Based on you proposal, scrape or collect your data:

1. One variable must be either: (40 pts)
    1. scraped from the web OR;
    2. collected from an API AND you must create one new variable that is "new" to the best of your knowledge (combination of other variables representing something new).

2. You must have at least 3 variables, but you may include as many as you want into you final dataset. Likely, you will want to include more to make graphs and regressions. (30pts)

3. You must *be able* to run a regression that makes some sense with this data (the regression doesn't have to be a complete model). Briefly describe one regression you would run with your variables. (**DO NOT** run a regression, yet). (15pts)

4. You must have one combined and cleaned dataset (15 pts)

You must submit one python notebook on how you scraped/gathered data from an api, and how you combined and cleaned you data. I should be able to run your code and reproduce your final data set.  

The other variables that you choose to include do not have to be collected by API or webscraped, but you do have to combine the files and clean the dataset with python.

Thus, you must submit:
- Your finalized data set (only one) (note: you may add more variables in the future).
- Your documented python notebook
- Any associated data files needed to produce the final dataset.

You will be evaluated on:
- Completeness of the data
- Quality of the code 
- The creativity of the new variable/webscraped data you gather

Be sure to upload ALL associated files for your code to run. I will run your code from beginning to end - make it easy for me to replicate your code.

In [63]:
import requests
import pandas as pd
import re
import time
from bs4 import BeautifulSoup

In [64]:
#Beginning of Webscraping Michelin Website
base_url = "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants" #storing base URL

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Connection": "keep-alive"
} #initalizing my headers

session = requests.Session() #opening browser session
all_rows = [] #creating empty list to store all restaurant data across all pages
page = 1 #starting on page 1
max_pages = 15 #safety stop so the loop cannot run forever

while page <= max_pages:
    # page 1 uses the base URL, later pages use /page/2, /page/3, etc.
    if page == 1:
        url = base_url
    else:
        url = f"{base_url}/page/{page}"

    print(f"\nScraping page {page}: {url}")

    response = session.get(url, headers=headers, timeout=30) #inital get request, setting headers, and setting a timeout of 30 seconds

    print("Status code:", response.status_code) #display status code
    print("Final URL:", response.url) #display the finale page URL
    print("Content-Type:", response.headers.get("Content-Type")) #display the type of content that has been returned
    print("Length:", len(response.text)) #display how much html I got back

    if len(response.text) == 0:
        print("Request returned empty HTML.") #Checking to see if HTML is empty so code doesn't crash later
        break

    # saves raw HTML if it is not empty so I do not lose a potential good pull
    with open(f"michelin_listing_raw_page_{page}.html", "w", encoding="utf-8") as f:
        f.write(response.text)
    print(f"Saved raw HTML as michelin_listing_raw_page_{page}.html")

    soup = BeautifulSoup(response.text, "html.parser")

    cards = soup.find_all("div", class_=lambda c: c and "js-restaurant__list_item" in c)
    print("Number of cards found:", len(cards)) #finding all the restaurant cards on the michelin website

    #if there are no cards found let me know so I can diagnose the issue
    #also stop the loop because it likely means there are no more pages with restaurant data
    if len(cards) == 0:
        print("No restaurant cards found.")
        break

    rows = [] #create empty list for just this page

    for card in cards:
        name_tag = card.find("h3") #find all the restaurant names
        a_tag = name_tag.find("a", href=True) if name_tag else None #also grabs the restaurnat's link if avaialable

        restaurant_name = a_tag.get_text(" ", strip=True) if a_tag else None #pulls out the restaurant name as text and remove surrounding spaces
        restaurant_url = ( #builds the full michelin URL by adding the base site and partial links
            "https://guide.michelin.com" + a_tag["href"]
            if a_tag and a_tag.get("href")
            else None
        )

        raw_card_text = card.get_text(" | ", strip=True) #extracts all visible text from the card
        cleaned_text = re.sub(r"\s+", " ", raw_card_text).strip() #cleans and seperates text to make it readable

        # location
        location_match = re.search(r"[A-Za-z'’&.\- ]+,\s*[A-Z]{2},\s*USA", cleaned_text) #finds the pattern in text for location and stores it
        location = location_match.group(0) if location_match else None

        # price + cuisine
        price_level = None #initializing new variables for price level and cuisine type
        cuisine = None

        price_cuisine_match = re.search(r"(\${1,4})\s*·\s*(.+)$", cleaned_text) #finds the patter for price and cuisine since they are listed next to each other on the website
        if price_cuisine_match:
            price_level = price_cuisine_match.group(1).strip() #stores the data for these variables group 1 is price level and group 2 is cuisine
            cuisine = price_cuisine_match.group(2).strip()

        # Michelin distinction
        michelin_distinction = None #initializing new variable for michelin ranking

        distinction_holder = card.find(attrs={"data-dtm-distinction": True}) #finds anything on the card to signify their respective rank
        if distinction_holder:
            michelin_distinction = distinction_holder.get("data-dtm-distinction") #if that value exists, stores it in this variable

        if not michelin_distinction: #if the rank isn't available on the card this loop uses the images on the card by accessing the file name to identify the rank
            for img in card.find_all("img"):
                src = (img.get("src") or "").lower()
                if "bib-gourmand" in src:
                    michelin_distinction = "Bib Gourmand"
                    break
                elif "green-star" in src:
                    michelin_distinction = "Green Star"
                    break
                elif "michelin-star" in src:
                    michelin_distinction = "Michelin Star"
                    break

        rows.append({
            "restaurant_name": restaurant_name,
            "restaurant_url": restaurant_url,
            "location": location,
            "price_level": price_level,
            "cuisine": cuisine,
            "michelin_distinction": michelin_distinction,
            "raw_card_text": cleaned_text,
            "page_number": page #adding page number in case I want to trace where each row came from
        }) #stores all restaurants data

    print(f"Rows scraped from page {page}:", len(rows))

    all_rows.extend(rows) #adds this page's rows to the full list of all pages

    page += 1 #move to the next Michelin results page
    time.sleep(2) #pause a little so I do not hammer the website too fast

print(f"\nStopped after page {page - 1}")
print("Total rows collected before cleaning:", len(all_rows))

#creating raw data frame from all scraped rows
df_michelin_raw = pd.DataFrame(all_rows)

print("Raw dataframe shape:", df_michelin_raw.shape)
print(df_michelin_raw.head())

#save raw scraped Michelin dataset
df_michelin_raw.to_csv("michelin_nyc_all_pages_raw.csv", index=False)
print("Saved as michelin_nyc_all_pages_raw.csv")

Scraping page 1: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants
Status code: 200
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants
Content-Type: text/html;charset=UTF-8
Length: 1103772
Saved raw HTML as michelin_listing_raw_page_1.html
Number of cards found: 53
Rows scraped from page 1: 53

Scraping page 2: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/2
Status code: 200
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/2
Content-Type: text/html;charset=UTF-8
Length: 1108923
Saved raw HTML as michelin_listing_raw_page_2.html
Number of cards found: 53
Rows scraped from page 2: 53

Scraping page 3: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/3
Status code: 200
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/3
Content-Type: text/html;charset=UTF-8
Length: 1107371
Saved raw HTML as michelin_listing_raw_page_3.html
Number of cards found: 53
Rows scraped from page 3: 53

Scraping page 4: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/4
Status code: 200
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/4
Content-Type: text/html;charset=UTF-8
Length: 1109306
Saved raw HTML as michelin_listing_raw_page_4.html
Number of cards found: 53
Rows scraped from page 4: 53

Scraping page 5: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/5
Status code: 200
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/5
Content-Type: text/html;charset=UTF-8
Length: 1109699
Saved raw HTML as michelin_listing_raw_page_5.html
Number of cards found: 53
Rows scraped from page 5: 53

Scraping page 6: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/6
Status code: 200
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/6
Content-Type: text/html;charset=UTF-8
Length: 1112126
Saved raw HTML as michelin_listing_raw_page_6.html
Number of cards found: 53
Rows scraped from page 6: 53

Scraping page 7: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/7
Status code: 200
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/7
Content-Type: text/html;charset=UTF-8
Length: 1104996
Saved raw HTML as michelin_listing_raw_page_7.html
Number of cards found: 53
Rows scraped from page 7: 53

Scraping page 8: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/8
Status code: 200
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/8
Content-Type: text/html;charset=UTF-8
Length: 748957
Saved raw HTML as michelin_listing_raw_page_8.html
Number of cards found: 19
Rows scraped from page 8: 19

Scraping page 9: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/9
Status code: 404
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/9
Content-Type: text/html;charset=UTF-8
Length: 638232
Saved raw HTML as michelin_listing_raw_page_9.html
Number of cards found: 9
Rows scraped from page 9: 9

Scraping page 10: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/10
Status code: 404
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/10
Content-Type: text/html;charset=UTF-8
Length: 637349
Saved raw HTML as michelin_listing_raw_page_10.html
Number of cards found: 9
Rows scraped from page 10: 9

Scraping page 11: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/11
Status code: 404
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/11
Content-Type: text/html;charset=UTF-8
Length: 637351
Saved raw HTML as michelin_listing_raw_page_11.html
Number of cards found: 9
Rows scraped from page 11: 9

Scraping page 12: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/12
Status code: 404
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/12
Content-Type: text/html;charset=UTF-8
Length: 637351
Saved raw HTML as michelin_listing_raw_page_12.html
Number of cards found: 9
Rows scraped from page 12: 9

Scraping page 13: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/13
Status code: 404
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/13
Content-Type: text/html;charset=UTF-8
Length: 637351
Saved raw HTML as michelin_listing_raw_page_13.html
Number of cards found: 9
Rows scraped from page 13: 9

Scraping page 14: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/14
Status code: 404
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/14
Content-Type: text/html;charset=UTF-8
Length: 637351
Saved raw HTML as michelin_listing_raw_page_14.html
Number of cards found: 9
Rows scraped from page 14: 9

Scraping page 15: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/15
Status code: 404
Final URL: https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/page/15
Content-Type: text/html;charset=UTF-8
Length: 637351
Saved raw HTML as michelin_listing_raw_page_15.html
Number of cards found: 9
Rows scraped from page 15: 9

Stopped after page 15
Total rows collected before cleaning: 453
Raw dataframe shape: (453, 8)
  restaurant_name                                     restaurant_url  \
0            Icca  https://guide.michelin.com/us/en/new-york-stat...
1            Icca  https://guide.michelin.com/us/en/new-york-stat...
2        Chambers  https://guide.michelin.com/us/en/new-york-stat...
3             Ito  https://guide.michelin.com/us/en/new-york-stat...
4           Atera  https://guide.michelin.com/us/en/new-york-stat...

             location price_level  \
0   New York, NY, USA        $$$$
1   New York, NY, USA        $$$$
2   New York, NY, USA         $$$
3   New York, NY, USA        $$$$
4   New York, NY, USA        $$$$

                                             cuisine michelin_distinction  \
0  Japanese | Reserve a table | Chambers | New Yo...               1 star
1                                           Japanese               1 star
2                                       Contemporary
3                                           Japanese
4                                       Contemporary               2 star

                                       raw_card_text  page_number
0  Reserve a table | Icca | New York, NY, USA | $...            1
1  Reserve a table | Icca | New York, NY, USA | $...            1
2  Reserve a table | Chambers | New York, NY, USA...            1
3          Ito | New York, NY, USA | $$$$ · Japanese            1
4  Reserve a table | Atera | New York, NY, USA | ...            1
Saved as michelin_nyc_all_pages_raw.csv

In [65]:
#load raw Michelin scrape
df_michelin = pd.read_csv("michelin_nyc_all_pages_raw.csv")

#quick check before cleaning
print("Shape before cleaning:", df_michelin.shape)
print(df_michelin.head())

if df_michelin.empty:
    print("No rows were extracted.")
else:
    #removes rows with missing restaurant name or url because those are essential
    df_michelin = df_michelin.dropna(subset=["restaurant_name", "restaurant_url"])

    #drops duplicate restaurants based on Michelin url
    df_michelin = df_michelin.drop_duplicates(subset="restaurant_url").reset_index(drop=True)

    #function to clean restaurant name, location, price, and cuisine from raw card text
    def clean_card_fields(text):
        if pd.isna(text):
            return pd.Series([None, None, None, None])

        #collapse messy whitespace into single spaces
        text = re.sub(r"\s+", " ", str(text)).strip()

        #remove "Reserve a table | " only if it appears at the beginning
        text = re.sub(r"^Reserve a table \| ", "", text)

        #split the text into chunks using the | separator
        parts = [p.strip() for p in text.split("|")]

        restaurant_name = None #initializing new variables
        location = None
        price_level = None
        cuisine = None
#analyzing the list parts to see the contents in which it contains 
        if len(parts) >= 1: 
            restaurant_name = parts[0]
#first part SHOULD be the name of the restaurant
        if len(parts) >= 2:
            location = parts[1]
#second part SHOULD be the location
        if len(parts) >= 3:
            last_part = parts[2]
#third part SHOULD be either the cuisine or the price level, but it varies on the site
            #split price and cuisine on the dot separator
            pc_match = re.match(r"(\${1,4})\s*·\s*(.+)", last_part)#looking for 1-4 dollar signs to identify the price level and if the cuisine is listed, seperated by a .
            if pc_match:#if theres a valid match
                price_level = pc_match.group(1).strip()#store the price level and remove any extra spaces
                cuisine = pc_match.group(2).strip()#store the cuisine and remove any extra spaces
            else:
                #fallback if separator is formatted strangely
                price_match = re.search(r"\${1,4}", last_part)
                if price_match:
                    price_level = price_match.group(0)
                    cuisine = last_part.replace(price_level, "").strip(" ·")

        return pd.Series([restaurant_name, location, price_level, cuisine])

    #apply the cleaning function to the raw card text column
    df_michelin[["restaurant_name_clean", "location_clean", "price_level_clean", "cuisine_clean"]] = (
        df_michelin["raw_card_text"].apply(clean_card_fields)
    )

    #overwrite original columns with cleaned values when available
    df_michelin["restaurant_name"] = df_michelin["restaurant_name_clean"].fillna(df_michelin["restaurant_name"])
    df_michelin["location"] = df_michelin["location_clean"].fillna(df_michelin["location"])
    df_michelin["price_level"] = df_michelin["price_level_clean"].fillna(df_michelin["price_level"])
    df_michelin["cuisine"] = df_michelin["cuisine_clean"].fillna(df_michelin["cuisine"])

    #clean Michelin distinction labels and reformat them 
    df_michelin["michelin_distinction"] = (
        df_michelin["michelin_distinction"]
        .replace("", pd.NA)
        .fillna("Selected Restaurants")
        .replace({
            "1 star": "One Star",
            "2 star": "Two Stars",
            "3 star": "Three Stars"
        })
    )

    #drop helper columns now that cleaning is done
    df_michelin = df_michelin.drop(columns=[
        "restaurant_name_clean",
        "location_clean",
        "price_level_clean",
        "cuisine_clean"
    ])

    #final duplicate check just in case
    df_michelin = df_michelin.drop_duplicates(subset="restaurant_url").reset_index(drop=True)

    #preview cleaned dataframe
    print("\nShape after cleaning:", df_michelin.shape)
    print(df_michelin[[
        "restaurant_name",
        "location",
        "price_level",
        "cuisine",
        "michelin_distinction",
        "page_number"
    ]].head(20))

    #save cleaned dataset
    df_michelin.to_csv("michelin_nyc_all_pages_clean.csv", index=False)
    print("\nSaved as michelin_nyc_all_pages_clean.csv")

Shape before cleaning: (453, 8)
  restaurant_name                                     restaurant_url  \
0            Icca  https://guide.michelin.com/us/en/new-york-stat...
1            Icca  https://guide.michelin.com/us/en/new-york-stat...
2        Chambers  https://guide.michelin.com/us/en/new-york-stat...
3             Ito  https://guide.michelin.com/us/en/new-york-stat...
4           Atera  https://guide.michelin.com/us/en/new-york-stat...

             location price_level  \
0   New York, NY, USA        $$$$
1   New York, NY, USA        $$$$
2   New York, NY, USA         $$$
3   New York, NY, USA        $$$$
4   New York, NY, USA        $$$$

                                             cuisine michelin_distinction  \
0  Japanese | Reserve a table | Chambers | New Yo...               1 star
1                                           Japanese               1 star
2                                       Contemporary                  NaN
3                                           Japanese                  NaN
4                                       Contemporary               2 star

                                       raw_card_text  page_number
0  Reserve a table | Icca | New York, NY, USA | $...            1
1  Reserve a table | Icca | New York, NY, USA | $...            1
2  Reserve a table | Chambers | New York, NY, USA...            1
3          Ito | New York, NY, USA | $$$$ · Japanese            1
4  Reserve a table | Atera | New York, NY, USA | ...            1

Shape after cleaning: (354, 8)
      restaurant_name           location price_level       cuisine  \
0                Icca  New York, NY, USA        $$$$      Japanese
1            Chambers  New York, NY, USA         $$$  Contemporary
2                 Ito  New York, NY, USA        $$$$      Japanese
3               Atera  New York, NY, USA        $$$$  Contemporary
4               Farra  New York, NY, USA         $$$  Contemporary
5                Huso  New York, NY, USA        $$$$  Contemporary
6            Manhatta  New York, NY, USA        $$$$  Contemporary
7    Jungsik New York  New York, NY, USA        $$$$        Korean
8            Tamarind  New York, NY, USA         $$$        Indian
9    One White Street  New York, NY, USA        $$$$  Contemporary
10          Crown Shy  New York, NY, USA         $$$  Contemporary
11  Maison Passerelle  New York, NY, USA        $$$$        French
12            Eulalie  New York, NY, USA         $$$        French
13            Cha Kee  New York, NY, USA          $$         Asian
14               Saga  New York, NY, USA        $$$$  Contemporary
15                Lei  New York, NY, USA          $$       Chinese
16            Bridges  New York, NY, USA         $$$  Contemporary
17      Dim Sum Go Go  New York, NY, USA          $$       Chinese
18         Carne Mare  New York, NY, USA        $$$$    Steakhouse
19             Yamada  New York, NY, USA        $$$$      Japanese

    michelin_distinction  page_number
0               One Star            1
1   Selected Restaurants            1
2   Selected Restaurants            1
3              Two Stars            1
4   Selected Restaurants            1
5               One Star            1
6   Selected Restaurants            1
7            Three Stars            1
8   Selected Restaurants            1
9   Selected Restaurants            1
10              One Star            1
11  Selected Restaurants            1
12  Selected Restaurants            1
13  Selected Restaurants            1
14             Two Stars            1
15  Selected Restaurants            1
16              One Star            1
17                   bib            1
18  Selected Restaurants            1
19              One Star            1

Saved as michelin_nyc_all_pages_clean.csv

In [66]:
print(df_michelin.info())
print(df_michelin.sample(10))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354 entries, 0 to 353
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   restaurant_name       354 non-null    object
 1   restaurant_url        354 non-null    object
 2   location              354 non-null    object
 3   price_level           354 non-null    object
 4   cuisine               354 non-null    object
 5   michelin_distinction  354 non-null    object
 6   raw_card_text         354 non-null    object
 7   page_number           354 non-null    int64
dtypes: int64(1), object(7)
memory usage: 22.3+ KB
None
              restaurant_name  \
263                 The Grill
180           Red Hook Tavern
327                  Tanoreen
140  Genesis House Restaurant
38                    Raoul's
191                   HanGawi
150                   Massara
172                    Upland
14                       Saga
88                      Frevo

                                        restaurant_url           location  \
263  https://guide.michelin.com/us/en/new-york-stat...  New York, NY, USA
180  https://guide.michelin.com/us/en/new-york-stat...  Brooklyn, NY, USA
327  https://guide.michelin.com/us/en/new-york-stat...  Brooklyn, NY, USA
140  https://guide.michelin.com/us/en/new-york-stat...  New York, NY, USA
38   https://guide.michelin.com/us/en/new-york-stat...  New York, NY, USA
191  https://guide.michelin.com/us/en/new-york-stat...  New York, NY, USA
150  https://guide.michelin.com/us/en/new-york-stat...  New York, NY, USA
172  https://guide.michelin.com/us/en/new-york-stat...  New York, NY, USA
14   https://guide.michelin.com/us/en/new-york-stat...  New York, NY, USA
88   https://guide.michelin.com/us/en/new-york-stat...  New York, NY, USA

    price_level                cuisine  michelin_distinction  \
263        $$$$               American  Selected Restaurants
180         $$$               American  Selected Restaurants
327          $$         Middle Eastern                   bib
140         $$$                 Korean  Selected Restaurants
38         $$$$                 French  Selected Restaurants
191          $$                 Korean                   bib
150         $$$                Italian  Selected Restaurants
172         $$$  Mediterranean Cuisine  Selected Restaurants
14         $$$$           Contemporary             Two Stars
88         $$$$           Contemporary              One Star

                                         raw_card_text  page_number
263    The Grill | New York, NY, USA | $$$$ · American            6
180  Red Hook Tavern | Brooklyn, NY, USA | $$$ · Am...            4
327  Reserve a table | Tanoreen | Brooklyn, NY, USA...            7
140  Genesis House Restaurant | New York, NY, USA |...            3
38   Reserve a table | Raoul's | New York, NY, USA ...            1
191  Reserve a table | HanGawi | New York, NY, USA ...            4
150        Massara | New York, NY, USA | $$$ · Italian            4
172  Reserve a table | Upland | New York, NY, USA |...            4
14   Reserve a table | Saga | New York, NY, USA | $...            1
88   Reserve a table | Frevo | New York, NY, USA | ...            2

In [126]:
#BEGINNING OF GOOGLE PLACES API WORK
import requests
import pandas as pd
import time

API_KEY = "AIzaSyCkvLVD433lBDxW4Mz9Ei2iN4x26hfcMU4"
TEXT_SEARCH_URL = "https://places.googleapis.com/v1/places:searchText"

def search_place(name, location):#defining the new function search_place  that will be used to find restaurants on google places
    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": API_KEY,
        "X-Goog-FieldMask": (
            "places.id,"
            "places.displayName,"
            "places.formattedAddress,"
            "places.rating,"
            "places.userRatingCount,"
            "places.priceLevel,"
            "places.primaryType,"
            "places.location,"
            "places.websiteUri"
        )
    }

    payload = {
        "textQuery": f"{name}, {location}"
    }

    r = requests.post(TEXT_SEARCH_URL, headers=headers, json=payload)
    r.raise_for_status()
    data = r.json()

    places = data.get("places", [])
    if not places:
        return None
 # usually take top candidate first, then sanity-check name/address
    p = places[0]#This takes the first result from Google’s list of matches, assuming that the first result is probably the best one. 

    return {#returns a dictionary of Google place ID Google’s version of the name, address, latitude, longitude, place type, average rating, total number of user ratings, etc.
        "place_id": p.get("id"),
        "google_name": p.get("displayName", {}).get("text"),
        "google_address": p.get("formattedAddress"),
        "google_rating": p.get("rating"),
        "google_user_rating_count": p.get("userRatingCount"),
        "google_price_level": p.get("priceLevel"),
        "google_primary_type": p.get("primaryType"),
        "google_lat": p.get("location", {}).get("latitude"),
        "google_lng": p.get("location", {}).get("longitude"),
        "google_website": p.get("websiteUri")
    }

results = []

for _, row in df_michelin.iterrows():#loop through each row of my michelin dataframe, ignore index
    try:
        result = search_place(row["restaurant_name"], row["location"])#call on the function i defined earlier

        if result is None:#handles cases where no matches were found If no match was found. The dictionary keeps the Michelin restaurant name, but fills all the Google-related fields with None.
            results.append({
                "restaurant_name": row["restaurant_name"],
                "place_id": None,
                "google_name": None,
                "google_address": None,
                "google_rating": None,
                "google_user_rating_count": None,
                "google_price_level": None,
                "google_primary_type": None,
                "google_lat": None,
                "google_lng": None,
                "google_website": None
            })
        else:
            result["restaurant_name"] = row["restaurant_name"]
            results.append(result)# This adds all key-value pairs from search_result into the current result dictionary.So now result contains both:Michelin info Google search info

        print("done:", row["restaurant_name"])#shows me which restaurants were completed

    except Exception as e:
        print("error with", row["restaurant_name"], ":", e)#shows me which restaurants there were issues with
        results.append({
            "restaurant_name": row["restaurant_name"],
            "place_id": None,
            "google_name": None,
            "google_address": None,
            "google_rating": None,
            "google_user_rating_count": None,
            "google_price_level": None,
            "google_primary_type": None,
            "google_lat": None,
            "google_lng": None,
            "google_website": None
        })

    time.sleep(0.2)

google_df = pd.DataFrame(results)
print(google_df.head())

done: Icca
done: Chambers
done: Ito
done: Atera
done: Farra
done: Huso
done: Manhatta
done: Jungsik New York
done: Tamarind
done: One White Street
done: Crown Shy
done: Maison Passerelle
done: Eulalie
done: Cha Kee
done: Saga
done: Lei
done: Bridges
done: Dim Sum Go Go
done: Carne Mare
done: Yamada
done: La Mercerie
done: Le Coucou
done: Muku
done: L’abeille à Côté
done: L’Abeille
done: Nyonya
done: Corima
done: Shabushabu Mayumon
done: Thai Diner
done: Cervo’s
done: Wayan
done: Potluck Club
done: Altro Paradiso
done: Ma•dé
done: Comal
done: Tolo
done: Dirt Candy
done: The River Café
done: Raoul's
done: Pinch Chinese
done: César
done: Sushi Ikumi
done: Torrisi
done: Forsythia
done: Russ & Daughters Cafe
done: The Musket Room
done: King
done: Estela
done: New
done: New
done: New
done: New
done: Ballato
done: Dhamaka
done: Raf's
done: Torien
done: Carbone
done: Lord's
done: 8282
done: Laliko
done: Ernesto's
done: Dame
done: C as in Charlie
done: Inga's Bar
done: Una Pizza Napoletana
done: Kabawa
done: Crevette
done: Sami & Susu
done: MayRee
done: Atla
done: Nami Nori
done: Yoshino
done: Minetta Tavern
done: Katz's
done: Bungalow
done: 63 Clinton
done: The Commerce Inn
done: Sushi Nakazawa New York
done: Ivan Ramen
done: Le Gigot
done: Little Myanmar
done: Family Meal at Blue Hill
done: Jeju Noodle Bar
done: I Sodi
done: Red Paper Clip
done: Via Carota
done: Secchu Yokota
done: Loring Place
done: Frevo
done: Adda
done: Shmoné
done: CheLi
done: Ariari
done: Soda Club
done: Tuome
done: MáLà Project
done: Nudibranch
done: Moody Tongue Sushi
done: Pylos
done: Ruffian
done: Noreetuh
done: Avant Garden
done: Sobaya
done: Miss Lily’s
done: Claud
done: Penny
done: Superiority Burger
done: The Office of Mr. Moto
done: 4 Charles Prime Rib
done: Smithereens
done: Bar Miller
done: Tsukimi
done: Pranakhon
done: Rosella
done: Kubeh
done: Semma
done: HAGS
done: Kanoyama
done: Momofuku Noodle Bar
done: Al Badawi
done: Bánh Anh Em
done: Yellow Rose
done: Bartolo
done: Odre
done: Soothr
done: Le B
done: Don Angie
done: Kosaka
done: Ishq
done: Bangkok Supper Club
done: Gage & Tollner
done: The Dining Room at The Guesthouse
done: Saint Julivert Fisherie
done: La Vara
done: Kanyakumari
done: Casa Mono
done: La Dong
done: Kyma
done: Sal Tang's
done: Portale
done: Genesis House Restaurant
done: abcV
done: Oceans
done: Carlotto
done: Oiji Mi
done: bōm
done: Gramercy Tavern
done: Rezdôra
done: Noda
done: odo
done: Massara
done: Mile End
done: Cosme
done: La Devozione: The Oval
done: Untable
done: Gus's Chop House
done: Crane Club
done: Noz 17
done: Novitá
done: Coqodaq
done: Aska
done: Cote
done: Jua
done: Shota Omakase
done: La Tête d’Or
done: Sunday in Brooklyn
done: Eleven Madison Park
done: Junoon
done: Glin Thai Bistro
done: Francie
done: Mesiba
done: Meadowsweet
done: Upland
done: Il Fiorista
done: Peter Luger
done: Café Kestrel
done: Atoboy
done: Ulivo
done: Café Carmellini
done: Miss Ada
done: Red Hook Tavern
done: Hungry Thirsty
done: Markette
done: Mango Bay
done: Atomix
done: Sailor
done: Norma Gastronomia Siciliana
done: Enso
done: 6 Restaurant
done: Theodora
done: Laser Wolf
done: HanGawi
done: The Four Horsemen
done: Joo Ok
done: Moono
done: Hav & Mar
done: Dons Bogam
done: Nōksu
done: Hyun
done: Hometown Bar B Que New York
done: Seoul Salon
done: Café Mars
done: Octo
done: Runner & Stone
done: Shalom Japan
done: Sawa
done: Lingo
done: Chez Ma Tante
done: KRU
done: Cho Dang Gol
done: Tonchin
done: Ci Siamo
done: Ai Fiori
done: Little Alley
done: Peak
done: Sofreh
done: Papa San
done: Uzuki
done: Madre
done: Place des Fêtes
done: Haenyeo
done: Oxomoco
done: Tempura Matsui
done: Restaurant Yuu
done: Peppercorn Station
done: Szechuan Gourmet
done: Chef's Table at Brooklyn Fare
done: Speedy Romeo
done: Rose Marie
done: Taqueria El Chato
done: Alta Calidad
done: Pierozek
done: ILIS
done: Sushi Sho
done: Wenwen
done: Gabriel Kreuther
done: Le Pavillon
done: Fausto
done: Sushi Yasuda
done: Jōji
done: Izakaya Futago
done: Bonnie's
done: The Lambs Club
done: Ammazzacaffè
done: Veerays
done: Casa Ora
done: Win Son
done: Meju
done: Fasano
done: Gui
done: Kochi
done: Mari
done: Hart's
done: Casa Enrique
done: Hupo
done: Runner Up
done: Jupiter
done: Kung Fu Little Steamed Buns Ramen
done: Le Rock
done: See No Evil Pizza
done: R40
done: Don Antonio
done: Le Bernardin
done: The Grill
done: Cafe Mado
done: Le Jardinier New York
done: Chalong
done: LORE
done: Lobster Club
done: Gallaghers
done: Santi
done: 53
done: The Modern
done: Hyderabadi Zaiqa
done: Caviar Russe
done: Benoit
done: YingTao
done: Aquavit
done: Four Twenty Five
done: Chavela’s
done: Roberta's
done: Agi's Counter
done: Chola
done: Sobre Masa
done: Marea
done: Per Se
done: Le Veau d'Or
done: Masa
done: Daphne's
done: Jean-Georges
done: Café Boulud
done: Lungi
done: Vert Frais
done: JoJo
done: Tatiana
done: Bayon
done: Daniel
done: The Leopard at Des Artistes
done: El Fish Marisqueria
done: Cafe Commerce
done: Tong
done: Risbo
done: Mission Ceviche
done: Bohemian Spirit
done: Persepolis
done: Chez Fifi
done: Gordo's Cantina
done: J.G. Melon
done: Kebab aur Sharab
done: Orsay
done: Sushi Akira
done: Sempre Oggi
done: Sushi Noz
done: Essential by Christophe
done: Covacha
done: Cardamom
done: Tha Phraya
done: Chuan Tian Xia
done: Ly Ly Vietnam Cookhouse
done: Olmo
done: Cafe Sabarsky
done: Eléa
done: Rolo's
done: East Harbor Seafood Palace
done: il Gigante
done: Chick Chick
done: Dagon
done: Tanoreen
done: Yemenat
done: Enoteca Maria
done: Phayul
done: Zaab Zaab
done: Miss Mamie's Spoonbread Too
done: Taverna Kyclades
done: Seppe Pizza Bar
done: Melba's
done: SaRanRom Thai
done: Lakruwana
done: Barawine
done: Neta Shari
done: Oso
done: Seis Vecinos
done: Caleta 111 Cevicheria
done: Asian Jewels
done: Jiang Nan
done: Alley 41
done: Tong Sam Gyup Goo Yi
done: Çka Ka Qëllu
done: Tra Di Noi
done: Legend of Taste
done: Patricia’s
done: Tobalá
done: Dubrovnik
done: Maria Restaurant
                      place_id      google_name  \
0  ChIJyRIhC_dbwokRqGoh89KPQME             icca
1  ChIJp1vZ3x5awokRpy0sG0r8_yU  Chambers Street
2  ChIJiW_7kM9bwokR9qMrG4XITL8              ITO
3  ChIJ_Y7rMCBawokR0mnRmN5kL2o            Atera
4  ChIJYw5z8rhbwokRvlPiJa21fuI            Farra

                           google_address  google_rating  \
0   20 Warren St, New York, NY 10007, USA            4.5
1          Chambers St, New York, NY, USA            NaN
2  75 Barclay St, New York, NY 10007, USA            4.5
3    77 Worth St, New York, NY 10013, USA            4.6
4    71 Worth St, New York, NY 10013, USA            4.6

   google_user_rating_count          google_price_level  google_primary_type  \
0                     136.0                        None  japanese_restaurant
1                       NaN                        None                 None
2                      92.0                        None           restaurant
3                     613.0  PRICE_LEVEL_VERY_EXPENSIVE  american_restaurant
4                     190.0                        None           restaurant

   google_lat  google_lng                    google_website restaurant_name
0   40.714301  -74.007684  https://www.exploretock.com/icca            Icca
1   40.715599  -74.009398                              None        Chambers
2   40.713085  -74.010140           https://itotribeca.com/             Ito
3   40.716900  -74.005563          http://www.ateranyc.com/           Atera
4   40.717031  -74.005697             https://farranyc.com/           Farra

In [127]:
merged = df_michelin.merge(google_df, on="restaurant_name", how="left")
print(merged.head())

  restaurant_name                                     restaurant_url  \
0            Icca  https://guide.michelin.com/us/en/new-york-stat...
1        Chambers  https://guide.michelin.com/us/en/new-york-stat...
2             Ito  https://guide.michelin.com/us/en/new-york-stat...
3           Atera  https://guide.michelin.com/us/en/new-york-stat...
4           Farra  https://guide.michelin.com/us/en/new-york-stat...

            location price_level       cuisine  michelin_distinction  \
0  New York, NY, USA        $$$$      Japanese              One Star
1  New York, NY, USA         $$$  Contemporary  Selected Restaurants
2  New York, NY, USA        $$$$      Japanese  Selected Restaurants
3  New York, NY, USA        $$$$  Contemporary             Two Stars
4  New York, NY, USA         $$$  Contemporary  Selected Restaurants

                                       raw_card_text  page_number  \
0  Reserve a table | Icca | New York, NY, USA | $...            1
1  Reserve a table | Chambers | New York, NY, USA...            1
2          Ito | New York, NY, USA | $$$$ · Japanese            1
3  Reserve a table | Atera | New York, NY, USA | ...            1
4     Farra | New York, NY, USA | $$$ · Contemporary            1

                      place_id      google_name  \
0  ChIJyRIhC_dbwokRqGoh89KPQME             icca
1  ChIJp1vZ3x5awokRpy0sG0r8_yU  Chambers Street
2  ChIJiW_7kM9bwokR9qMrG4XITL8              ITO
3  ChIJ_Y7rMCBawokR0mnRmN5kL2o            Atera
4  ChIJYw5z8rhbwokRvlPiJa21fuI            Farra

                           google_address  google_rating  \
0   20 Warren St, New York, NY 10007, USA            4.5
1          Chambers St, New York, NY, USA            NaN
2  75 Barclay St, New York, NY 10007, USA            4.5
3    77 Worth St, New York, NY 10013, USA            4.6
4    71 Worth St, New York, NY 10013, USA            4.6

   google_user_rating_count          google_price_level  google_primary_type  \
0                     136.0                        None  japanese_restaurant
1                       NaN                        None                 None
2                      92.0                        None           restaurant
3                     613.0  PRICE_LEVEL_VERY_EXPENSIVE  american_restaurant
4                     190.0                        None           restaurant

   google_lat  google_lng                    google_website
0   40.714301  -74.007684  https://www.exploretock.com/icca
1   40.715599  -74.009398                              None
2   40.713085  -74.010140           https://itotribeca.com/
3   40.716900  -74.005563          http://www.ateranyc.com/
4   40.717031  -74.005697             https://farranyc.com/

In [128]:
merged.head()

,restaurant_name,restaurant_url,location,price_level,cuisine,michelin_distinction,raw_card_text,page_number,place_id,google_name,google_address,google_rating,google_user_rating_count,google_price_level,google_primary_type,google_lat,google_lng,google_website
0,Icca,https://guide.michelin.com/us/en/new-york-stat...,"New York, NY, USA",$$$$,Japanese,One Star,"Reserve a table | Icca | New York, NY, USA | $...",1,ChIJyRIhC_dbwokRqGoh89KPQME,icca,"20 Warren St, New York, NY 10007, USA",4.5,136.0,None,japanese_restaurant,40.714301,-74.007684,https://www.exploretock.com/icca
1,Chambers,https://guide.michelin.com/us/en/new-york-stat...,"New York, NY, USA",$$$,Contemporary,Selected Restaurants,"Reserve a table | Chambers | New York, NY, USA...",1,ChIJp1vZ3x5awokRpy0sG0r8_yU,Chambers Street,"Chambers St, New York, NY, USA",NaN,NaN,None,None,40.715599,-74.009398,None
2,Ito,https://guide.michelin.com/us/en/new-york-stat...,"New York, NY, USA",$$$$,Japanese,Selected Restaurants,"Ito | New York, NY, USA | $$$$ · Japanese",1,ChIJiW_7kM9bwokR9qMrG4XITL8,ITO,"75 Barclay St, New York, NY 10007, USA",4.5,92.0,None,restaurant,40.713085,-74.010140,https://itotribeca.com/
3,Atera,https://guide.michelin.com/us/en/new-york-stat...,"New York, NY, USA",$$$$,Contemporary,Two Stars,"Reserve a table | Atera | New York, NY, USA | ...",1,ChIJ_Y7rMCBawokR0mnRmN5kL2o,Atera,"77 Worth St, New York, NY 10013, USA",4.6,613.0,PRICE_LEVEL_VERY_EXPENSIVE,american_restaurant,40.716900,-74.005563,http://www.ateranyc.com/
4,Farra,https://guide.michelin.com/us/en/new-york-stat...,"New York, NY, USA",$$$,Contemporary,Selected Restaurants,"Farra | New York, NY, USA | $$$ · Contemporary",1,ChIJYw5z8rhbwokRvlPiJa21fuI,Farra,"71 Worth St, New York, NY 10013, USA",4.6,190.0,None,restaurant,40.717031,-74.005697,https://farranyc.com/

In [93]:
merged

,restaurant_name,restaurant_url,location,price_level,cuisine,michelin_distinction,raw_card_text,page_number,place_id,google_name,google_address,google_rating,google_user_rating_count,google_price_level,google_primary_type,google_lat,google_lng,google_website
0,Icca,https://guide.michelin.com/us/en/new-york-stat...,"New York, NY, USA",$$$$,Japanese,One Star,"Reserve a table | Icca | New York, NY, USA | $...",1,ChIJyRIhC_dbwokRqGoh89KPQME,icca,"20 Warren St, New York, NY 10007, USA",4.5,136.0,None,japanese_restaurant,40.714301,-74.007684,https://www.exploretock.com/icca
1,Chambers,https://guide.michelin.com/us/en/new-york-stat...,"New York, NY, USA",$$$,Contemporary,Selected Restaurants,"Reserve a table | Chambers | New York, NY, USA...",1,ChIJp1vZ3x5awokRpy0sG0r8_yU,Chambers Street,"Chambers St, New York, NY, USA",NaN,NaN,None,None,40.715599,-74.009398,None
2,Ito,https://guide.michelin.com/us/en/new-york-stat...,"New York, NY, USA",$$$$,Japanese,Selected Restaurants,"Ito | New York, NY, USA | $$$$ · Japanese",1,ChIJiW_7kM9bwokR9qMrG4XITL8,ITO,"75 Barclay St, New York, NY 10007, USA",4.5,92.0,None,restaurant,40.713085,-74.010140,https://itotribeca.com/
3,Atera,https://guide.michelin.com/us/en/new-york-stat...,"New York, NY, USA",$$$$,Contemporary,Two Stars,"Reserve a table | Atera | New York, NY, USA | ...",1,ChIJ_Y7rMCBawokR0mnRmN5kL2o,Atera,"77 Worth St, New York, NY 10013, USA",4.6,613.0,PRICE_LEVEL_VERY_EXPENSIVE,american_restaurant,40.716900,-74.005563,http://www.ateranyc.com/
4,Farra,https://guide.michelin.com/us/en/new-york-stat...,"New York, NY, USA",$$$,Contemporary,Selected Restaurants,"Farra | New York, NY, USA | $$$ · Contemporary",1,ChIJYw5z8rhbwokRvlPiJa21fuI,Farra,"71 Worth St, New York, NY 10013, USA",4.6,190.0,None,restaurant,40.717031,-74.005697,https://farranyc.com/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,Legend of Taste,https://guide.michelin.com/us/en/new-york-stat...,"Queens, NY, USA",$$,Chinese,bib,"Legend of Taste | Queens, NY, USA | $$ · Chinese",8,ChIJRUDshWKKwokRKEDd6H2RAmE,Legend of Taste,"20-02 Utopia Pkwy, Whitestone, NY 11357, USA",4.4,373.0,PRICE_LEVEL_MODERATE,chinese_restaurant,40.779595,-73.794179,https://legendoftasteup.com/
362,Patricia’s,https://guide.michelin.com/us/en/new-york-stat...,"Bronx, NY, USA",$$$,Italian-American,Selected Restaurants,"Reserve a table | Patricia’s | Bronx, NY, USA ...",8,ChIJ5aH0oPv1wokRx2wGcb1NqFE,Patricia's of Morris Park,"1082 Morris Park Ave, Bronx, NY 10461, USA",4.3,412.0,PRICE_LEVEL_MODERATE,italian_restaurant,40.849121,-73.853301,https://patriciasofmorrispark.com/
363,Tobalá,https://guide.michelin.com/us/en/new-york-stat...,"Bronx, NY, USA",$$$,Mexican,Selected Restaurants,"Reserve a table | Tobalá | Bronx, NY, USA | $$...",8,ChIJPbOOFvPzwokRttFt-acm5qo,Tobala,"3732 Riverdale Ave, Bronx, NY 10463, USA",4.5,372.0,None,mexican_restaurant,40.887490,-73.906872,http://tobalanyc.com/
364,Dubrovnik,https://guide.michelin.com/us/en/new-york-stat...,"New Rochelle, NY, USA",$$,Croatian,Selected Restaurants,"Reserve a table | Dubrovnik | New Rochelle, NY...",8,ChIJFdppi6GNwokRniWwhWXgovg,Dubrovnik,"721 Main St, New Rochelle, NY 10801, USA",4.7,1083.0,PRICE_LEVEL_MODERATE,croatian_restaurant,40.903611,-73.789167,http://dubrovnikny.com/
365,Maria Restaurant,https://guide.michelin.com/us/en/new-york-stat...,"New Rochelle, NY, USA",$$,Italian,Selected Restaurants,Reserve a table | Maria Restaurant | New Roche...,8,ChIJ64RnV16NwokRtRsZaZbZzRw,Maria Restaurant,"11 Huguenot St, New Rochelle, NY 10801, USA",4.5,426.0,PRICE_LEVEL_MODERATE,italian_restaurant,40.914330,-73.773779,https://www.marianewrochelle.com/

In [94]:
merged.to_csv("michelin_google_merged.csv", index=False)

In [137]:
import requests
import pandas as pd
import numpy as np
import time
import re
from math import radians, sin, cos, sqrt, atan2

API_KEY = "AIzaSyCkvLVD433lBDxW4Mz9Ei2iN4x26hfcMU4"
NEARBY_URL = "https://places.googleapis.com/v1/places:searchNearby"
#function to normalize names for comparison sake, makes all lowercase, removes punctuation, and extra spaces
def normalize_name(name):
    if pd.isna(name):
        return ""
    name = str(name).lower().strip()
    name = re.sub(r'[^a-z0-9\s]', '', name)
    name = re.sub(r'\s+', ' ', name)
    return name
#function to calculate distance (km) from one restaurant to another 
def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c
#matches micheline cuisine types to google place cuisines to compare same types of food
# strict cuisine mapping: no generic "restaurant" except fallback cases
CUISINE_TYPE_MAP = {
    "Japanese": ["japanese_restaurant", "sushi_restaurant"],
    "Italian": ["italian_restaurant", "pizza_restaurant"],
    "French": ["french_restaurant"],
    "Chinese": ["chinese_restaurant", "dim_sum_restaurant", "chinese_noodle_restaurant"],
    "Korean": ["korean_restaurant"],
    "Mexican": ["mexican_restaurant"],
    "Indian": ["indian_restaurant"],
    "Thai": ["thai_restaurant"],
    "Seafood": ["seafood_restaurant"],
    "Steakhouse": ["steak_house"],
    "Pizza": ["pizza_restaurant"],
    "Sushi": ["sushi_restaurant", "japanese_restaurant"],
    "American": ["american_restaurant", "fine_dining_restaurant"],
    "Contemporary": ["fine_dining_restaurant", "american_restaurant", "french_restaurant", "italian_restaurant"],
    "Contemporary American": ["fine_dining_restaurant", "american_restaurant"]
}
#Identifies previous matches I have found that are not accurate to later filter them out
BAD_TYPES = [
    "cafe",
    "bakery",
    "coffee_shop",
    "meal_takeaway",
    "fast_food_restaurant",
    "food_court",
    "sandwich_shop",
    "pizza_delivery",
    "delivery_restaurant",
    "bar",
    "hamburger_restaurant",
    "chicken_wings_restaurant"
]
#Secondary bad matches I had found in previous trials to ensure they don't make it through to the final data frame
BAD_NAME_WORDS = [
    "chipotle",
    "sarku",
    "le pain quotidien",
    "burger",
    "wings",
    "fridge",
    "market",
    "grill",
    "halal food"
]
#function to see if the restaurant is not a viable comparsion based on my above criteria 
def has_bad_name(name):
    norm = normalize_name(name)
    return any(word in norm for word in BAD_NAME_WORDS)
#function to find restaurants near my michelin restaurants, within 1.2km raidus of the restaurant's lat n long, maximum 20 matches.
def nearby_search(lat, lng, radius_m=1200, max_results=20):
    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": API_KEY,
        "X-Goog-FieldMask": (
            "places.id,"#place ID
            "places.displayName,"#name
            "places.formattedAddress,"#address
            "places.rating,"#avg. rating
            "places.userRatingCount,"#number of ratings 
            "places.priceLevel,"#price level
            "places.primaryType,"#cuisine identifier
            "places.location,"#lat n long
            "places.websiteUri"#website if need to check if good match
        )
    }

    payload = {
        "includedTypes": ["restaurant"],#only include restaurants 
        "maxResultCount": max_results,
        "rankPreference": "DISTANCE",#show me the closest first
        "locationRestriction": {
            "circle": {#within a circular distance
                "center": {
                    "latitude": float(lat),
                    "longitude": float(lng)
                },
                "radius": float(radius_m)
            }
        }
    }

    r = requests.post(NEARBY_URL, headers=headers, json=payload)#API Request
    r.raise_for_status()#status
    data = r.json()#conversion 

    places = data.get("places", [])#sees if anything was returned and makes sure code doesn't crash if not
    rows = []

    for p in places:#for all the returned restaurants 
        rows.append({#get and store the data for their ID, name, address, etc.
            "place_id": p.get("id"),
            "google_name": p.get("displayName", {}).get("text"),
            "google_address": p.get("formattedAddress"),
            "google_rating": p.get("rating"),
            "google_user_rating_count": p.get("userRatingCount"),
            "google_price_level": p.get("priceLevel"),
            "google_primary_type": p.get("primaryType"),
            "google_lat": p.get("location", {}).get("latitude"),
            "google_lng": p.get("location", {}).get("longitude"),
            "google_website": p.get("websiteUri")
        })

    return pd.DataFrame(rows)#conversts dictionaries to pandas df
#function to validate matches of michelin restaurants 
def is_michelin_match(candidate_name, michelin_names):
    norm = normalize_name(candidate_name)#cleans and standardizes all the returned names
    return any(m in norm or norm in m for m in michelin_names if m) #check and see if the michelin name is contained in the canditate name and vice versa to remove duplicates
#function to score candidates for comparisons based on quality, populairty, and proximity
def score_candidate(row):
    score = 0 #starts at 0

    if pd.notna(row["google_user_rating_count"]): #checks the number of ratings, and if nonexistent
        score += min(row["google_user_rating_count"] / 100, 15)#increases scores based on number of reviews, 100 revies = 1 point, total 15 possibe points

    if pd.notna(row["google_rating"]): #checks avg rating and if exists
        score += row["google_rating"] #increases score by ratings because I want restaurants of similar stature to compare 

    if pd.notna(row["distance_km"]): #checks distance and if exists
        score -= row["distance_km"] * 12 #this is a penalty for further away restaurants 1 km -12 points 

    return score
#builds a set of michelin restaurant names, removes missing, and normalizes them all
michelin_names = set(merged["restaurant_name"].dropna().map(normalize_name))
#makes a copy so I don't accidentally overwrite orignal data 
work_df = merged.copy()


all_controls = []

for i, (_, mic) in enumerate(work_df.iterrows(), start=1): #for all the michelin restaurants, ignore index, add a counter 

    if pd.isna(mic["google_lat"]) or pd.isna(mic["google_lng"]): #if they are missing lat and long skip them and let me know 
        print(f"{i}: skipped {mic['restaurant_name']} because lat/lng missing")
        continue
#stores all the target data to varaibles so its easier to read later
    target_name = mic["restaurant_name"]
    target_cuisine = mic["cuisine"]
    target_price = mic["google_price_level"]
    target_lat = mic["google_lat"]
    target_lng = mic["google_lng"]

    allowed_types = CUISINE_TYPE_MAP.get(target_cuisine, []) #lookup the micheline cuisine in my mapping dictionary 
#search for nearby restaurants using my function around the michelin restauants coordinates 
    try:
        candidates = nearby_search(
            lat=target_lat,
            lng=target_lng,
            radius_m=1200,
            max_results=20
        )

        if candidates.empty: #if its empty say there's no candidates for that restauant 
            print(f"{i}: no candidates for {target_name}")
            continue

        candidates["norm_name"] = candidates["google_name"].map(normalize_name) #normalize the candidate names 

        # remove Michelin restaurants
        candidates = candidates[
            ~candidates["google_name"].apply(lambda x: is_michelin_match(x, michelin_names))
        ].copy()
        #remove some of the restaurant types I got back previously that are not valid comparisons 
        candidates = candidates[
            ~candidates["google_primary_type"].isin([
        "taco_restaurant",
        "fast_food_restaurant",
        "meal_takeaway",
        "pizza_restaurant",
        "hamburger_restaurant",
        "sandwich_shop",
        "chicken_restaurant"
            ])
        ].copy()
        candidates = candidates[ #requires the presence of price info
            candidates["google_price_level"].notna()
        ].copy()

        # remove bad types
        candidates = candidates[
            ~candidates["google_primary_type"].isin(BAD_TYPES)
        ].copy()
        #keep only restaurants with a decent number of reviews
        candidates = candidates[
            (candidates["google_user_rating_count"] >= 200)
]

        # remove bad chain / casual names
        candidates = candidates[
            ~candidates["google_name"].apply(has_bad_name)
            ].copy()

        # require usable data
        candidates = candidates[
        ~candidates["google_primary_type"].isin([
        "deli",
        "pizza_restaurant",
        "hamburger_restaurant",
        "fast_food_restaurant",
        "meal_takeaway"
                    ])
                ]

        if candidates.empty: #if these filters removed everything say there's no comparisons
            print(f"{i}: no usable candidates for {target_name}")
            continue

        # exact price match required
        if pd.notna(target_price):
            candidates = candidates[
                candidates["google_price_level"] == target_price
            ].copy()

        if candidates.empty: #let me know if there's no price matches 
            print(f"{i}: no exact price matches for {target_name}")
            continue

        # cuisine/type filter if available
        if allowed_types:
            typed = candidates[
                candidates["google_primary_type"].isin(allowed_types)
            ].copy()

            if not typed.empty:
                candidates = typed.copy()

        candidates["distance_km"] = candidates.apply( #computes distance
            lambda r: haversine(target_lat, target_lng, r["google_lat"], r["google_lng"]) #use my haversine function to calculate distance between target and candidates 
            if pd.notna(r["google_lat"]) and pd.notna(r["google_lng"]) else np.nan, #prevents crash if missing
            axis=1
        )

        candidates["match_score"] = candidates.apply(score_candidate, axis=1) #scores candidates

        best = candidates.sort_values(
            by=["match_score", "distance_km", "google_user_rating_count"],
            ascending=[False, True, False] #higher scores first, closer first, more reviews first
        ).head(2).copy() #sorts the candidates and keeps the top 2 candidates for each michelin restaurant 
#adds michelin match info to the chosen controls 
        best["matched_to_michelin"] = target_name 
        best["matched_to_cuisine"] = target_cuisine
        best["matched_to_price"] = target_price

        all_controls.append(best) #save chosen matches into a master list

        partial_df = pd.concat(all_controls, ignore_index=True) #saves partial results 
        partial_df.to_csv("controls_partial_strict.csv", index=False)

        print(f"{i}: done {target_name}") #progress message for each restaurant

        time.sleep(0.1)

    except Exception as e: #catches errors in try block to prevent crashes 
        print(f"{i}: error with {target_name}: {e}")

controls_df = pd.concat(all_controls, ignore_index=True) if all_controls else pd.DataFrame() #combine all final controls
controls_df = controls_df.drop_duplicates(subset=["place_id"]) #removes duplicates 

print(controls_df.head())

controls_df.to_csv("non_michelin_controls_strict.csv", index=False)
print("saved non_michelin_controls_strict.csv")

1: done Icca
2: done Chambers
3: done Ito
4: done Atera
5: done Farra
6: done Huso
7: no exact price matches for Manhatta
8: done Jungsik New York
9: done Tamarind
10: done One White Street
11: no exact price matches for Crown Shy
12: done Maison Passerelle
13: done Eulalie
14: done Cha Kee
15: no exact price matches for Saga
16: done Lei
17: done Bridges
18: done Dim Sum Go Go
19: no exact price matches for Carne Mare
20: done Yamada
21: done La Mercerie
22: no exact price matches for Le Coucou
23: done Muku
24: done L’abeille à Côté
25: done L’Abeille
26: done Nyonya
27: done Corima
28: done Shabushabu Mayumon
29: done Thai Diner
30: done Cervo’s
31: done Wayan
32: done Potluck Club
33: done Altro Paradiso
34: done Ma•dé
35: done Comal
36: done Tolo
37: done Dirt Candy
38: no exact price matches for The River Café
39: done Raoul's
40: done Pinch Chinese
41: done César
42: done Sushi Ikumi
43: done Torrisi
44: done Forsythia
45: done Russ & Daughters Cafe
46: no exact price matches for The Musket Room
47: done King
48: no exact price matches for Estela
49: done New
50: done New
51: done New
52: error with New: 'google_primary_type'
53: done New
54: done New
55: done New
56: error with New: 'google_primary_type'
57: done New
58: done New
59: done New
60: error with New: 'google_primary_type'
61: done New
62: done New
63: done New
64: error with New: 'google_primary_type'
65: no exact price matches for Ballato
66: no exact price matches for Dhamaka
67: done Raf's
68: done Torien
69: no exact price matches for Carbone
70: done Lord's
71: done 8282
72: done Laliko
73: done Ernesto's
74: done Dame
75: done C as in Charlie
76: done Inga's Bar
77: done Una Pizza Napoletana
78: done Kabawa
79: done Crevette
80: done Sami & Susu
81: done MayRee
82: done Atla
83: done Nami Nori
84: done Yoshino
85: no exact price matches for Minetta Tavern
86: done Katz's
87: done Bungalow
88: done 63 Clinton
89: done The Commerce Inn
90: no exact price matches for Sushi Nakazawa New York
91: done Ivan Ramen
92: done Le Gigot
93: done Little Myanmar
94: done Family Meal at Blue Hill
95: done Jeju Noodle Bar
96: done I Sodi
97: done Red Paper Clip
98: done Via Carota
99: done Secchu Yokota
100: no exact price matches for Loring Place
101: done Frevo
102: done Adda
103: done Shmoné
104: done CheLi
105: done Ariari
106: done Soda Club
107: done Tuome
108: done MáLà Project
109: done Nudibranch
110: done Moody Tongue Sushi
111: done Pylos
112: done Ruffian
113: no exact price matches for Noreetuh
114: done Avant Garden
115: done Sobaya
116: done Miss Lily’s
117: done Claud
118: done Penny
119: done Superiority Burger
120: no exact price matches for The Office of Mr. Moto
121: no exact price matches for 4 Charles Prime Rib
122: done Smithereens
123: done Bar Miller
124: done Tsukimi
125: done Pranakhon
126: done Rosella
127: done Kubeh
128: done Semma
129: done HAGS
130: done Kanoyama
131: no exact price matches for Momofuku Noodle Bar
132: done Al Badawi
133: done Bánh Anh Em
134: done Yellow Rose
135: done Bartolo
136: done Odre
137: done Soothr
138: no exact price matches for Le B
139: done Don Angie
140: no exact price matches for Kosaka
141: done Ishq
142: done Bangkok Supper Club
143: done Gage & Tollner
144: done The Dining Room at The Guesthouse
145: done Saint Julivert Fisherie
146: no exact price matches for La Vara
147: done Kanyakumari
148: done Casa Mono
149: done La Dong
150: done Kyma
151: done Sal Tang's
152: done Portale
153: done Genesis House Restaurant
154: done abcV
155: no exact price matches for Oceans
156: done Carlotto
157: done Oiji Mi
158: done bōm
159: no exact price matches for Gramercy Tavern
160: done Rezdôra
161: no exact price matches for Noda
162: no exact price matches for odo
163: done Massara
164: done Mile End
165: no exact price matches for Cosme
166: done La Devozione: The Oval
167: done Untable
168: done Gus's Chop House
169: done Crane Club
170: done Noz 17
171: no exact price matches for Novitá
172: no exact price matches for Coqodaq
173: done Aska
174: no exact price matches for Cote
175: no exact price matches for Jua
176: done Shota Omakase
177: done La Tête d’Or
178: done Sunday in Brooklyn
179: no exact price matches for Eleven Madison Park
180: no exact price matches for Junoon
181: done Glin Thai Bistro
182: done Francie
183: done Mesiba
184: no exact price matches for Meadowsweet
185: done Upland
186: done Il Fiorista
187: no exact price matches for Peter Luger
188: done Café Kestrel
189: done Atoboy
190: done Ulivo
191: done Café Carmellini
192: done Miss Ada
193: done Red Hook Tavern
194: no exact price matches for Hungry Thirsty
195: done Markette
196: done Mango Bay
197: no exact price matches for Atomix
198: done Sailor
199: done Norma Gastronomia Siciliana
200: done Enso
201: done 6 Restaurant
202: done Theodora
203: done Laser Wolf
204: done HanGawi
205: done The Four Horsemen
206: done Joo Ok
207: done Moono
208: done Hav & Mar
209: done Dons Bogam
210: done Nōksu
211: no exact price matches for Hyun
212: done Hometown Bar B Que New York
213: done Seoul Salon
214: done Café Mars
215: no exact price matches for Octo
216: done Runner & Stone
217: no exact price matches for Shalom Japan
218: done Sawa
219: done Lingo
220: done Chez Ma Tante
221: done KRU
222: done Cho Dang Gol
223: done Tonchin
224: no exact price matches for Ci Siamo
225: no exact price matches for Ai Fiori
226: done Little Alley
227: done Peak
228: done Sofreh
229: done Papa San
230: done Uzuki
231: done Madre
232: done Place des Fêtes
233: done Haenyeo
234: done Oxomoco
235: no exact price matches for Tempura Matsui
236: done Restaurant Yuu
237: done Peppercorn Station
238: done Szechuan Gourmet
239: no exact price matches for Chef's Table at Brooklyn Fare
240: done Speedy Romeo
241: done Rose Marie
242: done Taqueria El Chato
243: done Alta Calidad
244: done Pierozek
245: done ILIS
246: done Sushi Sho
247: done Wenwen
248: no exact price matches for Gabriel Kreuther
249: no exact price matches for Le Pavillon
250: no exact price matches for Fausto
251: no exact price matches for Sushi Yasuda
252: done Jōji
253: done Izakaya Futago
254: done Bonnie's
255: done The Lambs Club
256: done Ammazzacaffè
257: done Veerays
258: done Casa Ora
259: done Win Son
260: done Meju
261: no exact price matches for Fasano
262: done Gui
263: done Kochi
264: no exact price matches for Mari
265: no exact price matches for Hart's
266: done Casa Enrique
267: done Hupo
268: done Runner Up
269: done Jupiter
270: done Kung Fu Little Steamed Buns Ramen
271: done Le Rock
272: done See No Evil Pizza
273: done R40
274: done Don Antonio
275: no exact price matches for Le Bernardin
276: no exact price matches for The Grill
277: done Cafe Mado
278: no exact price matches for Le Jardinier New York
279: done Chalong
280: done LORE
281: no exact price matches for Lobster Club
282: no exact price matches for Gallaghers
283: done Santi
284: done 53
285: done The Modern
286: done Hyderabadi Zaiqa
287: done Caviar Russe
288: no exact price matches for Benoit
289: done YingTao
290: no exact price matches for Aquavit
291: done Four Twenty Five
292: done Chavela’s
293: done Roberta's
294: done Agi's Counter
295: done Chola
296: done Sobre Masa
297: no exact price matches for Marea
298: no exact price matches for Per Se
299: done Le Veau d'Or
300: no exact price matches for Masa
301: done Daphne's
302: error with Jean-Georges: 'google_primary_type'
303: no exact price matches for Café Boulud
304: done Lungi
305: done Vert Frais
306: no exact price matches for JoJo
307: done Tatiana
308: no exact price matches for Bayon
309: done Daniel
310: no exact price matches for The Leopard at Des Artistes
311: done El Fish Marisqueria
312: done Cafe Commerce
313: done Tong
314: done Risbo
315: done Mission Ceviche
316: done Bohemian Spirit
317: done Persepolis
318: done Chez Fifi
319: done Gordo's Cantina
320: done J.G. Melon
321: done Kebab aur Sharab
322: done Orsay
323: done Sushi Akira
324: done Sempre Oggi
325: no exact price matches for Sushi Noz
326: done Essential by Christophe
327: done Covacha
328: done Cardamom
329: done Tha Phraya
330: done Chuan Tian Xia
331: done Ly Ly Vietnam Cookhouse
332: done Olmo
333: done Cafe Sabarsky
334: done Eléa
335: done Rolo's
336: done East Harbor Seafood Palace
337: done il Gigante
338: done Chick Chick
339: no exact price matches for Dagon
340: done Tanoreen
341: no exact price matches for Yemenat
342: done Enoteca Maria
343: done Phayul
344: done Zaab Zaab
345: done Miss Mamie's Spoonbread Too
346: done Taverna Kyclades
347: no exact price matches for Seppe Pizza Bar
348: done Melba's
349: done SaRanRom Thai
350: error with Lakruwana: 'google_primary_type'
351: done Barawine
352: done Neta Shari
353: done Oso
354: done Seis Vecinos
355: no exact price matches for Caleta 111 Cevicheria
356: done Asian Jewels
357: done Jiang Nan
358: done Alley 41
359: done Tong Sam Gyup Goo Yi
360: done Çka Ka Qëllu
361: done Tra Di Noi
362: done Legend of Taste
363: done Patricia’s
364: done Tobalá
365: done Dubrovnik
366: done Maria Restaurant
                      place_id                        google_name  \
0  ChIJv3vgwFZbwokRwP07bRgRYdM                           Artesano
1  ChIJSYuuSx9awokRyrrOFTGg0GY                         Gran Morsi
2  ChIJ-0VhGB9awokRksxfZJBvigE                   Serafina Tribeca
3  ChIJV1VdJB9awokRsucxnGK_eTE                           Mudville
4  ChIJ6e4q1BhawokRWWDyNSiQ4yo  Benares Tribeca Indian Restaurant

                                   google_address  google_rating  \
0  90 Chambers St Unit A, New York, NY 10007, USA            4.6
1           22 Warren St, New York, NY 10007, USA            4.4
2          95 W Broadway, New York, NY 10007, USA            4.4
3        126 Chambers St, New York, NY 10007, USA            4.2
4           45 Murray St, New York, NY 10007, USA            4.2

   google_user_rating_count    google_price_level  google_primary_type  \
0                     995.0  PRICE_LEVEL_MODERATE  peruvian_restaurant
1                     611.0  PRICE_LEVEL_MODERATE   italian_restaurant
2                    1562.0  PRICE_LEVEL_MODERATE   italian_restaurant
3                     926.0  PRICE_LEVEL_MODERATE  american_restaurant
4                    2312.0  PRICE_LEVEL_MODERATE    indian_restaurant

   google_lat  google_lng                       google_website  \
0   40.714477  -74.007437       http://artesanorestaurant.com/
1   40.714315  -74.007766            http://www.granmorsi.com/
2   40.715505  -74.008945  https://www.serafinarestaurant.com/
3   40.715208  -74.008923           http://www.mudvilleny.com/
4   40.714149  -74.009208           http://www.benaresnyc.com/

                           norm_name  distance_km  match_score  \
0                           artesano     0.028640    14.206325
1                         gran morsi     0.007048    10.425422
2                   serafina tribeca     0.039568    18.925185
3                           mudville     0.059021    12.751746
4  benares tribeca indian restaurant     0.142000    17.495998

  matched_to_michelin matched_to_cuisine matched_to_price
0                Icca           Japanese             None
1                Icca           Japanese             None
2            Chambers       Contemporary             None
3            Chambers       Contemporary             None
4                 Ito           Japanese             None
saved non_michelin_controls_strict.csv

In [138]:
controls_df = controls_df.drop_duplicates(subset=["place_id"])
controls_df = controls_df[
    controls_df["google_price_level"].notna()
]
controls_df[[
    "matched_to_michelin",
    "google_name",
    "google_address",
    "google_price_level",
    "google_primary_type",
    "google_rating",
    "google_user_rating_count",
    "distance_km"
]].head(30)

,matched_to_michelin,google_name,google_address,google_price_level,google_primary_type,google_rating,google_user_rating_count,distance_km
0,Icca,Artesano,"90 Chambers St Unit A, New York, NY 10007, USA",PRICE_LEVEL_MODERATE,peruvian_restaurant,4.6,995.0,0.028640
1,Icca,Gran Morsi,"22 Warren St, New York, NY 10007, USA",PRICE_LEVEL_MODERATE,italian_restaurant,4.4,611.0,0.007048
2,Chambers,Serafina Tribeca,"95 W Broadway, New York, NY 10007, USA",PRICE_LEVEL_MODERATE,italian_restaurant,4.4,1562.0,0.039568
3,Chambers,Mudville,"126 Chambers St, New York, NY 10007, USA",PRICE_LEVEL_MODERATE,american_restaurant,4.2,926.0,0.059021
4,Ito,Benares Tribeca Indian Restaurant,"45 Murray St, New York, NY 10007, USA",PRICE_LEVEL_MODERATE,indian_restaurant,4.2,2312.0,0.142000
5,Ito,CUT by Wolfgang Puck,"99 Church St, New York, NY 10007, USA",PRICE_LEVEL_EXPENSIVE,restaurant,4.4,780.0,0.071595
6,Atera,69 Leonard Street,"69 Leonard St, New York, NY 10013, USA",PRICE_LEVEL_VERY_EXPENSIVE,japanese_restaurant,4.5,241.0,0.089175
7,Farra,Two Hands,"251 Church St, New York, NY 10013, USA",PRICE_LEVEL_MODERATE,australian_restaurant,4.4,1304.0,0.087934
8,Farra,Tara Kitchen Tribeca,"253 Church St, New York, NY 10013, USA",PRICE_LEVEL_MODERATE,moroccan_restaurant,4.6,268.0,0.097726
9,Huso,Forgione,"30 Hudson St, New York, NY 10013, USA",PRICE_LEVEL_EXPENSIVE,american_restaurant,4.6,764.0,0.153864
10,Huso,Gigino Trattoria,"323 Greenwich St, New York, NY 10013, USA",PRICE_LEVEL_MODERATE,italian_restaurant,4.4,604.0,0.012192
11,Jungsik New York,American Cut,"363 Greenwich St, New York, NY 10013, USA",PRICE_LEVEL_VERY_EXPENSIVE,steak_house,4.5,1028.0,0.085559
12,Tamarind,Locanda Verde Tribeca,"377 Greenwich St, New York, NY 10013, USA",PRICE_LEVEL_EXPENSIVE,italian_restaurant,4.4,2317.0,0.119998
13,Tamarind,Mr Chow,"121 Hudson St, New York, NY 10013, USA",PRICE_LEVEL_EXPENSIVE,restaurant,3.9,693.0,0.111961
14,One White Street,Frenchette,"241 W Broadway, New York, NY 10013, USA",PRICE_LEVEL_EXPENSIVE,french_restaurant,4.3,1278.0,0.045120
15,One White Street,Terra,"225 W Broadway, New York, NY 10013, USA",PRICE_LEVEL_MODERATE,italian_restaurant,4.3,844.0,0.013327
16,Maison Passerelle,Serafina Financial District,"30 Broad St, New York, NY 10004, USA",PRICE_LEVEL_MODERATE,italian_restaurant,4.6,1049.0,0.139464
18,Cha Kee,Mei Lai Wah,"41 Mott St, New York, NY 10013, USA",PRICE_LEVEL_INEXPENSIVE,chinese_restaurant,4.4,3787.0,0.015495
19,Cha Kee,House of Joy,"28 Pell St, New York, NY 10013, USA",PRICE_LEVEL_INEXPENSIVE,dim_sum_restaurant,4.1,1368.0,0.050928
20,Lei,Nom Wah Tea Parlor,"13 Doyers St, New York, NY 10013, USA",PRICE_LEVEL_INEXPENSIVE,dim_sum_restaurant,4.2,5244.0,0.011662
21,Lei,Mei Lai Wah | Wonton Noodle Garden,"23 Pell St, New York, NY 10038, USA",PRICE_LEVEL_INEXPENSIVE,chinese_restaurant,4.3,1950.0,0.023879
22,Bridges,Ajisen Ramen,"14 Mott St, New York, NY 10013, USA",PRICE_LEVEL_INEXPENSIVE,ramen_restaurant,4.6,2588.0,0.046627
23,Bridges,Tasty Hand - Pulled Noodles,"1 Doyers St, New York, NY 10013, USA",PRICE_LEVEL_INEXPENSIVE,chinese_noodle_restaurant,4.4,1472.0,0.028088
24,Dim Sum Go Go,Golden Unicorn,"18 E Broadway, New York, NY 10002, USA",PRICE_LEVEL_MODERATE,dim_sum_restaurant,4.0,3509.0,0.064977
25,Yamada,Joe's Shanghai,"46 Bowery, New York, NY 10013, USA",PRICE_LEVEL_INEXPENSIVE,chinese_restaurant,4.2,6143.0,0.055805
26,Yamada,Deluxe Green Bo,"66 Bayard St, New York, NY 10013, USA",PRICE_LEVEL_INEXPENSIVE,chinese_restaurant,4.3,1627.0,0.071851
27,La Mercerie,NOMO Kitchen,"9 Crosby St, New York, NY 10013, USA",PRICE_LEVEL_EXPENSIVE,american_restaurant,3.9,1282.0,0.166228
28,Muku,Wolfgang's Steakhouse,"409 Greenwich St, New York, NY 10013, USA",PRICE_LEVEL_VERY_EXPENSIVE,steak_house,4.4,1661.0,0.073957
30,L’abeille à Côté,Yves,"385 Greenwich St, New York, NY 10013, USA",PRICE_LEVEL_MODERATE,french_restaurant,4.1,323.0,0.185404
32,Nyonya,Tomiño Taberna Gallega,"192 Grand St, New York, NY 10013, USA",PRICE_LEVEL_MODERATE,spanish_restaurant,4.6,2268.0,0.050341

In [140]:
print(michelin_final.columns)
print(controls_final.columns)

print(michelin_final.columns[michelin_final.columns.duplicated()])
print(controls_final.columns[controls_final.columns.duplicated()])

Index(['restaurant_name', 'michelin_distinction', 'rating', 'review_count',
       'price_level', 'type', 'michelin'],
      dtype='object')
Index(['restaurant_name', 'rating', 'review_count', 'price_level', 'type',
       'michelin', 'michelin_distinction'],
      dtype='object')
Index([], dtype='object')
Index([], dtype='object')

In [141]:
#Remove duplicate columns and only keep first verion of each one
michelin_final = michelin_final.loc[:, ~michelin_final.columns.duplicated()].copy()
controls_final = controls_final.loc[:, ~controls_final.columns.duplicated()].copy()

In [139]:
#CLEANING AND MERGING DATA
#takes only relevant data from orignal webscrape data 
michelin_final = merged[[
    "restaurant_name",
    "michelin_distinction",
    "google_rating",
    "google_user_rating_count",
    "google_price_level",
    "google_primary_type"
]].copy()

michelin_final["michelin"] = 1 #creates binary variable for being on the michelin guide set to 1 
#standardizes column names 
michelin_final = michelin_final.rename(columns={
    "google_rating": "rating",
    "google_user_rating_count": "review_count",
    "google_price_level": "price_level",
    "google_primary_type": "type"
})
#takes only relevant data
controls_final = controls_df[[
    "google_name",
    "google_rating",
    "google_user_rating_count",
    "google_price_level",
    "google_primary_type"
]].copy()

controls_final["michelin"] = 0 #creates binary variable for being on the michelin guide and sets to 0 
controls_final["michelin_distinction"] = "None" #states there is no michelin distinction 
controls_final = controls_final.rename(columns={#cleanes column names to match webscraped data 
    "google_name": "restaurant_name",
    "google_rating": "rating",
    "google_user_rating_count": "review_count",
    "google_price_level": "price_level",
    "google_primary_type": "type"
})

final_df = pd.concat([ #merges data sets 
    michelin_final,
    controls_final[[
        "restaurant_name",
        "michelin_distinction",
        "rating",
        "review_count",
        "price_level",
        "type",
        "michelin"
    ]]
], ignore_index=True)

In [134]:
final_df

,restaurant_name,michelin_distinction,rating,review_count,price_level,type,michelin
0,Icca,One Star,4.5,136.0,None,japanese_restaurant,1
1,Chambers,Selected Restaurants,NaN,NaN,None,None,1
2,Ito,Selected Restaurants,4.5,92.0,None,restaurant,1
3,Atera,Two Stars,4.6,613.0,PRICE_LEVEL_VERY_EXPENSIVE,american_restaurant,1
4,Farra,Selected Restaurants,4.6,190.0,None,restaurant,1
...,...,...,...,...,...,...,...
786,Healthy Fresh,None,4.4,353.0,PRICE_LEVEL_MODERATE,restaurant,0
787,Cocina Chente,None,4.4,721.0,PRICE_LEVEL_MODERATE,mexican_restaurant,0
788,Colombian House,None,4.7,3276.0,PRICE_LEVEL_MODERATE,colombian_restaurant,0
789,Rebecca's Café,None,4.6,210.0,PRICE_LEVEL_MODERATE,mexican_restaurant,0
790,Spadaro Roman Kitchen,None,4.6,337.0,PRICE_LEVEL_MODERATE,italian_restaurant,0

In [142]:
# keep only rows with usable rating + review count
analysis_df = final_df.dropna(subset=["rating", "review_count"]).copy()

#require price level for price-based comparisons
analysis_price_df = analysis_df.dropna(subset=["price_level"]).copy()

print(analysis_df.head())
print(analysis_df.shape)
analysis_df.to_csv("analysis_df.csv", index=False)

  restaurant_name  michelin_distinction  rating  review_count  \
0            Icca              One Star     4.5         136.0
2             Ito  Selected Restaurants     4.5          92.0
3           Atera             Two Stars     4.6         613.0
4           Farra  Selected Restaurants     4.6         190.0
5            Huso              One Star     4.7         296.0

                  price_level                    type  michelin
0                        None     japanese_restaurant         1
2                        None              restaurant         1
3  PRICE_LEVEL_VERY_EXPENSIVE     american_restaurant         1
4                        None              restaurant         1
5                        None  fine_dining_restaurant         1
(790, 7)

In [143]:
analysis_df

,restaurant_name,michelin_distinction,rating,review_count,price_level,type,michelin
0,Icca,One Star,4.5,136.0,None,japanese_restaurant,1
2,Ito,Selected Restaurants,4.5,92.0,None,restaurant,1
3,Atera,Two Stars,4.6,613.0,PRICE_LEVEL_VERY_EXPENSIVE,american_restaurant,1
4,Farra,Selected Restaurants,4.6,190.0,None,restaurant,1
5,Huso,One Star,4.7,296.0,None,fine_dining_restaurant,1
...,...,...,...,...,...,...,...
787,Healthy Fresh,None,4.4,352.0,PRICE_LEVEL_MODERATE,restaurant,0
788,Cocina Chente,None,4.4,721.0,PRICE_LEVEL_MODERATE,mexican_restaurant,0
789,Colombian House,None,4.7,3276.0,PRICE_LEVEL_MODERATE,colombian_restaurant,0
790,Rebecca's Café,None,4.6,210.0,PRICE_LEVEL_MODERATE,mexican_restaurant,0
791,Spadaro Roman Kitchen,None,4.6,337.0,PRICE_LEVEL_MODERATE,italian_restaurant,0